In [5]:
import numpy as np

#### Create an array of 10 zeros

In [8]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [14]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [19]:
np.ones((8))*5

array([5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [23]:
arr=np.arange(10,51)

In [25]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 503

In [29]:
arr=np.arange(10,51,2)

In [31]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [35]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [48]:
np.random.rand(1)

array([0.27912738])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [57]:
np.random.randn(5,5)

array([[-0.53744777, -1.60435911, -0.96327683, -0.30857767, -1.59057405],
       [-0.74361237,  0.76238242, -2.00740369, -0.14363112,  0.48991799],
       [-0.65309049,  0.61113134,  2.37074269,  2.03289615, -0.38938084],
       [ 1.05234475, -2.90799204,  0.29334962,  1.01246079, -0.31664695],
       [ 1.41256959,  1.56917392,  1.57964399, -0.0790275 , -0.59264337]])

#### Create the following matrix:

In [11]:

arr = np.arange(0.01,1.01,0.01).reshape(10,10)

arr

#### Create an array of 20 linearly spaced points between 0 and 1:

In [20]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [23]:
arr=np.arange(1,26).reshape(5,5)

In [25]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
arr[0:5,0:6]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
arr[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [33]:
arr[3,4]

20

In [45]:
arr[0:3,1]

array([ 2,  7, 12])

In [47]:
arr[4]

array([21, 22, 23, 24, 25])

In [49]:
arr[3:6]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
arr.sum()

325

#### Get the standard deviation of the values in mat

In [53]:
np.std(arr)

7.211102550927978

#### Get the sum of all the columns in mat

In [73]:
arr.sum(0)

array([55, 60, 65, 70, 75])

#### Get the sum of all the rows in mat

In [67]:
arr.sum(1)

array([ 15,  40,  65,  90, 115])

#### Get the sum of the first row in mat

In [69]:
arr[0].sum()

15

In [77]:
 arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])